output_dir:  "/mnt/test/user/zhengsixiao/trained_model/I2V"
pretrained_model_path: "/mnt/test/user/zhengsixiao/pretrained_model/stable-diffusion-2-1-base"


noise_scheduler_kwargs:
  num_train_timesteps:    1000
  beta_start:             0.00085
  beta_end:               0.012
  beta_schedule:          "linear"
  steps_offset:           1
  clip_sample:            false
  rescale_betas_zero_snr: false     # true if using zero terminal snr
  timestep_spacing:       "leading" # "trailing" if using zero terminal snr
  prediction_type:        "epsilon" # "v_prediction" if using zero terminal snr

train_data:
  dataset:             "pororo"
  image_root_path:   "/mnt/test/user/zhengsixiao/datasets/pororo_png"
  mode: "train"
  sample_size:       256
  sample_duration:   null
  sample_fps:        null
  sample_stride:     [1, 5]
  sample_n_frames:   5
  num_workers: 32

test_data:
  dataset:             "pororo"
  image_root_path:   "/mnt/test/user/zhengsixiao/datasets/pororo_png"
  mode: "test"
  sample_size:       256
  num_workers: 32

validation_data:
  prompts:
    - 
      - "loopy sings and smells cherry pie. loopy is holding a cherry."
      - "loopy puts cherry on a pie. loopy is done with the pie."
      - "loopy puts pie on the table. loopy looks very happy. there are bread a book apples and a pie on the table."
      - "loopy tastes pie and loopy thinks it is delicious. loopy turns over the page."
      - "loopy marvels at the picture on the book. loopy eats a piece of pie."
    - 
      - "loopy lowers her head and shakes her head. loopy looks sad."
      - "someone calls loopy. loopy looks at the door."
      - "crong pororo poby and eddy have come over to loopy's house."
      - "loopy does not look happy even thought her friends have visited her."
      - "loopy invites her friends in."

  path_to_first_frames:
    - "assets/pororo/ori_img_0000_0.png"
    - "assets/pororo/ori_img_0001_0.png"

  num_inference_steps: 50
  ddim_eta: 0.0
  guidance_scale_txt: 7.5
  guidance_scale_img: 1.0
  guidance_rescale: 0.0
  frame_stride: 1

trainable_modules:
  - "all"
  # - "conv3ds."
  # - "tempo_attns."

resume_from_checkpoint: null

unet_additional_kwargs:
  variant: null
  n_temp_heads: 8
  augment_temporal_attention: true
  temp_pos_embedding: "rotary" # "rotary" or "sinusoidal"
  first_frame_condition_mode: "conv2d"
  use_frame_stride_condition: false
  noise_sampling_method: "pyoco_mixed" # "vanilla" or "pyoco_mixed" or "pyoco_progressive"
  noise_alpha: 1.5
  use_motion_condition: true
  use_temporal: 
    temporal_attn: true
    temporal_conv: true

cfg_random_null_text_ratio: 0.1
cfg_random_null_img_ratio: 0.1

use_ema: true
ema_decay: 0.9999

learning_rate:    5.e-5
train_batch_size: 6
test_batch_size: 23
gradient_accumulation_steps: 2
max_grad_norm: 0.5

max_train_epoch:      50
max_train_steps:      40000
checkpointing_epochs: -1
checkpointing_steps:  4000
validation_steps:     4000
checkpoints_total_limit: 2
use_text_cross_attention: "FSText"
num_layers_FStext: 4
FStext_layer_depth: 2
FStext_layer_temporal: 
  - false
  - true
FStext_layer_causal: 
  - false
  - false

zero_init_storyflow_adapter: true
zero_init_FSText: true

seed: 42
mixed_precision: "bf16"

enable_xformers_memory_efficient_attention: true

is_image: false
is_debug: false

sampling_kwargs:
  height: 256
  width: 256
  n_frames: 5
  steps: 50
  ddim_eta: 0.0
  guidance_scale_txt: 7.5
  guidance_scale_img: 1.0
  guidance_rescale: 0.0
  num_videos_per_prompt: 1
  frame_stride: 1

frameinit_kwargs:
  enable: false
  camera_motion: null
  noise_level: 850
  filter_params:
    method: 'gaussian'
    d_s: 0.25
    d_t: 0.25
